### First Request
POST http://0.0.0.0:8008/api/v1/document
Accept: application/json
Content-Type: application/json

{
  "owner_user_id": "b283af46-e02c-4a3a-b05b-a3776b806441",
  "name": "War&Pice",
  "code": "0.1"
}

### Second Request
POST http://0.0.0.0:8000/api/v1/document
Accept: application/json
Content-Type: application/json

{
  "owner_user_id": "90d98938-81da-41a8-b239-1604bb406b64",
  "name": "Tom Soyer",
  "code": "Bar"
}

### Brocke Request
POST http://0.0.0.0:8000/api/v1/document
Accept: application/json
Content-Type: application/json

{
  "owner_user_id": "809abc00-c847-4979-9fc5-ebf1cb9a3069",
  "name": "Tom Soyer",
  "code": 1
}