"""initial

Revision ID: 2c624562e5ee
Revises: 4afe2e2e651c
Create Date: 2024-08-05 08:18:10.526791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c624562e5ee"
down_revision: Union[str, None] = "4afe2e2e651c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_document_name_code", "document", type_="unique")
    op.create_unique_constraint(
        op.f("uq_document_owner_user_id_name_code"),
        "document",
        ["owner_user_id", "name", "code"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_document_owner_user_id_name_code"), "document", type_="unique"
    )
    op.create_unique_constraint(
        "uq_document_name_code", "document", ["name", "code"]
    )
    # ### end Alembic commands ###
